// Obtener todas las peliculas
GET http://localhost:3000

GET http://localhost:3000/api/movies

// Filtrar por id
GET http://localhost:3000/api/movies/c83c8be5-f3d9-4fb6-884d-7249c452d920

// Filtrar por genero
GET http://localhost:3000/api/movies?genre=action


// Post de varias peliculas
POST http://localhost:3000/api/movies
Content-Type: application/json

[
    {
        "title": "Toy Story",
        "director": "John Lasseter",
        "year": 1995,
        "genre": "Animation",
        "rating": 8.3,
        "duration": 81
    },
    {
        "title": "The Lion King",
        "director": "Roger Allers",
        "year": 1994,
        "genre": "Animation",
        "rating": 8.5,
        "duration": 88
    }
]

// Post de una sola pelicula
POST http://localhost:3000/api/movies
Content-Type: application/json

{
    "title": "John Wick",
    "directorId": "3868d2b0-dcab-4fba-920a-a0dfd44e90c8",
    "year": 2014,
    "genre": "Action",
    "rating": 7.4,
    "duration": 101
}

// Patch de una pelicula
PATCH http://localhost:3000/api/movies/c83c8be5-f3d9-4fb6-884d-7249c452d920
Content-Type: application/json

{
    "rating": 8.5
}

// Patch con error
PATCH http://localhost:3000/api/movies/c83c8be5-f3d9-4fb6-884d-7249c452d920
Content-Type: application/json

{
    "year": "2015"
}

// Delete de una pelicula
DELETE http://localhost:3000/api/movies/c83c8be5-f3d9-4fb6-884d-7249c452d920

// Get de todos los directores
GET http://localhost:3000/api/directors

GET http://localhost:3000/api/directors/3868d2b0-dcab-4fba-920a-a0dfd44e90c8

POST http://localhost:3000/api/directors
Content-Type: application/json

{
    "name": "Chad Stahelski",
    "birthDate" : "1968-09-20",
    "email": "chadstahelski@gmail.com",
    "phone": "555-555-555"
}

PATCH http://localhost:3000/api/directors/3868d2b0-dcab-4fba-920a-a0dfd44e90c8
Content-Type: application/json

{
    "phone": "555-555-556"
}